FROM golang:1.25-alpine3.21

RUN apk add --no-cache git
RUN go install github.com/air-verse/air@latest

WORKDIR /go/src/chaincode
COPY go.mod go.sum ./
RUN go mod download

WORKDIR /go/src/chaincode/chaincode

EXPOSE 9999
CMD ["air", "-c", ".air.toml"]
